# Generated by Django 5.0.6 on 2024-05-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='visibilidade',
            field=models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='public', max_length=10),
        ),
    ]
