# Generated by Django 5.0.6 on 2024-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('autor', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('data_publi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
