# Generated by Django 5.0.6 on 2024-06-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeApp01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
